services:
    postgres:
        image: postgres
        container_name: itask-app-postgres
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: postgres
            POSTGRES_DB: itask-app
        ports:
            - '5432:5432'
        volumes:
            - './.postgres-data:/var/lib/postgresql/data'
